### ISSUE TITLE
没有SXXshadowsocks-dns

### ISSUE THREAD

**Issue by tixo** [goodbest/Merlin-SS-config#1]
安装完ss后，只有init.d目录下没有SXXshadowsocks-dns启动文件，也没有shadowsocks-dns.json ，但是有SXXshadowsocks 和 shadowsocks.json。 不知如何配置ss-tunnel

**Comment by goodbest** [comment]
把后者复制一个即可，改掉里面参数内容。

**Comment by tixo** [comment]
ok，另外generated目录下没有china_iptable的脚本
